"use client";
import { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import localFont from "next/font/local";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { QueryClient, QueryClientProvider } from "react-query";
const queryClient = new QueryClient();
import { Provider, atom } from "jotai";
import { useAtom } from "jotai";

export const metadata: Metadata = {
  title: "پنل مدیریت",
  description: "Generated by create next app",
};

const IRANSansX = localFont({
  src: [
    {
      path: "./../assets/IRANSansX/IRANSansX-Thin.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "./../assets/IRANSansX/IRANSansX-Light.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "./../assets/IRANSansX/IRANSansX-UltraLight.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "./../assets/IRANSansX/IRANSansX-Medium.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./../assets/IRANSansX/IRANSansX-Light.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./../assets/IRANSansX/IRANSansX-Bold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "./../assets/IRANSansX/IRANSansX-ExtraBold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "./../assets/IRANSansX/IRANSansX-Black.woff2",
      weight: "800",
      style: "normal",
    },
  ],
});

export const pageTitle = atom("داشبورد");

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Provider initialValues={pageTitle}>
      <html lang="en" dir="rtl">
        <body suppressHydrationWarning={true} className={IRANSansX.className}>
          <QueryClientProvider client={queryClient}>
            <ToastContainer />
            <SessionProvider>{children}</SessionProvider>
          </QueryClientProvider>
        </body>
      </html>
    </Provider>
  );
}
