import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./../globals.scss";
import Navbar from "../components/design/Navbar";
import Footer from "../components/design/Footer";
import "react-toastify/dist/ReactToastify.css";
import BottomNav from "../components/design/BottomNav";
import { ToastContainer } from "react-toastify";
import { Provider } from "jotai";
import Providers from "../components/Providers";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  manifest: "/manifest.json",
  title: "جهیزان | خرید اقساطی جهیزیه",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa-IR" dir="rtl">
      <link
        rel="apple-touch-startup-image"
        href="/apple-launch-1125x2436.png"
      ></link>
      <body>
        <Providers>
          <Provider>
            <Navbar />
            <ToastContainer />
            <BottomNav />
            <NextTopLoader color="#20ac73" />
            {children}
            <Footer />
          </Provider>
        </Providers>
      </body>
    </html>
  );
}
