import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./../globals.scss";
import Navbar from "../components/design/Navbar";
import Footer from "../components/design/Footer";
import localFont from "next/font/local";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "جهیزان",
  description: "Generated by create next app",
};

const IRANSansX = localFont({
  src: [
    {
      path: "./../assets/IRANSansX/IRANSansX-Thin.woff2",
      weight: "100",
      style: "normal",
    },
    {
      path: "./../assets/IRANSansX/IRANSansX-Light.woff2",
      weight: "200",
      style: "normal",
    },
    {
      path: "./../assets/IRANSansX/IRANSansX-UltraLight.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "./../assets/IRANSansX/IRANSansX-Medium.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./../assets/IRANSansX/IRANSansX-Light.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./../assets/IRANSansX/IRANSansX-Bold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "./../assets/IRANSansX/IRANSansX-ExtraBold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "./../assets/IRANSansX/IRANSansX-Black.woff2",
      weight: "800",
      style: "normal",
    },
  ],
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" dir="rtl">
      <body className={IRANSansX.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
