import { redirect } from "next/navigation";
import { getServerSession } from "next-auth";
import SignInForm from "./components/BaseForm";
import NextAuth from "next-auth/next";
import { authOptions } from "@/app/api/auth/[...nextauth]/authOptions";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "جهیزان | ورود",
  description: "Generated by create next app",
};
const LoginPage = async () => {
  const session = await getServerSession(authOptions);

  if (session?.token) {
    return redirect("/");
  }
  return <SignInForm session={session} />;
};

export default LoginPage;
